import { Flex } from '@chakra-ui/layout';
import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>World Trip</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Flex>
        <h1>Eae</h1>
      </Flex>
    </div>
  );
}
